---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by omegarogue.
--- DateTime: 14.02.22 10:47
---

local rawget     = rawget

local helpers = {}

function helpers.wrequire(t, k)
    return rawget(t, k) or require(t._NAME .. '.' .. k)
end


return helpers