---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by omegarogue.
--- DateTime: 15.02.22 10:06
---

local wrequire     = require("omegavoid.helpers").wrequire
local setmetatable = setmetatable

local widget = { _NAME = "omegavoid.widget.powerline" }

return setmetatable(widget, { __index = wrequire })