---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by omegarogue.
--- DateTime: 15.02.22 10:07
---

local setmetatable = setmetatable
local os = os
local fixed = require("wibox.layout.fixed")
local seperator = require("omegavoid.widget.powerline.seperator")
local gtable = require("gears.table")
local lain = require('lain')
local markup = lain.util.markup
local beautiful = require("beautiful")
local wibox = require('wibox')
local segment = { mt = {} }



local function new(left,current_color,next_color,fg,...)
    local w = fixed.horizontal()
    gtable.crush(w, segment, true)

    local base_fg = fg or beautiful.fg_normal
    local curr_bg = current_color or beautiful.bg_normal
    local next_bg = next_color or beautiful.bg_normal
    local sep  = seperator(left,curr_bg,next_bg, base_fg)
    local container = wibox.widget{
        widget = wibox.container.background,
        bg = curr_bg,
        {
            layout = wibox.layout.fixed.horizontal,
            ...
        }
    }
    if fg then
        container.fg = fg
    end
    if left then
        w:add(container)
    end
    w:add(sep)
    if not left then
        w:add(container)
    end

    return w
end

function segment.mt:__call(...)
    return new(...)
end

return setmetatable(segment, segment.mt)