---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by omegarogue.
--- DateTime: 15.02.22 10:14
---

local setmetatable = setmetatable
--local os = os
local textbox = require("wibox.widget.textbox")
--local gears = require("gears")
--local wibox = require("wibox")
local gtable = require("gears.table")
local lain = require('lain')
local markup = lain.util.markup
local beautiful = require("beautiful")
local seperator = { mt = {} }

function seperator.gen_markup(left, current_color, next_color, fg)
    local curr_bg = current_color or beautiful.bg_normal
    local next_bg = next_color or beautiful.bg_normal
    local base_fg = fg or beautiful.fg_normal
    if left then
        if curr_bg == next_bg then
            return markup.fontcolor(beautiful.powerline_font, base_fg, curr_bg, beautiful.powerline_left_soft or "\u{E0B1}")
        end
        return markup.fontcolor(beautiful.powerline_font, curr_bg, next_bg, beautiful.powerline_left_hard or "\u{E0B0}")
    end
    if curr_bg == next_bg then
        return markup.fontcolor(beautiful.powerline_font, next_bg, curr_bg, beautiful.powerline_right_soft or "\u{E0B2}")
    end
    return markup.fontcolor(beautiful.powerline_font, base_fg, curr_bg, beautiful.powerline_right_hard or "\u{E0B3}")
end

local function new(left, current_color, next_color, fg)
    local w = textbox()
    gtable.crush(w, seperator, true)
    w:set_markup(seperator.gen_markup(left,current_color,next_color,fg))
    return w
end
function seperator.mt:__call(...)
    return new(...)
end

return setmetatable(seperator, seperator.mt)

