---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by omegarogue.
--- DateTime: 14.02.22 10:46
---

local wrequire     = require("omegavoid.helpers").wrequire
local setmetatable = setmetatable

local widget = { _NAME = "omegavoid.widget" }

return setmetatable(widget, { __index = wrequire })