---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by omegarogue.
--- DateTime: 14.02.22 10:46
---

local wrequire     = require("omegavoid.helpers").wrequire
local setmetatable = setmetatable

local menu = { _NAME = "omegavoid.global-menu" }

return setmetatable(menu, { __index = wrequire })
